[tool.poetry]
name = "inscriptis"
version = "2.4.0"
description = "inscriptis - HTML to text converter."
authors = ["Albert Weichselbraun <albert.weichselbraun@fhgr.ch>", "Fabian Odoni <fabian.odoni@fhgr.ch>"]
license = "Apache 2.0"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.8 || ^3.9 || ^3.10 || ^3.11 || ^3.12"
requests = "^2.31.0"
lxml = "^5.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# code formatting with black
[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311", "py312"]
include = '''
  ^scripts/
  ^src/
  ^tests/
'''
